name: Multiarch build

on:
  push:
      
env:
  IMAGE_NAME: test-multi-arch
  IMAGE_TAG: latest
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: mayurwaghmode111

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64
        
      - name: Docker build and publish
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          no-cache: true
          push: false
          tags: dummy:mummy
